name: auto-release
on:
  push:
  pull_request:

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:

      - name: auto-release
        uses: alecsammon/gh-action-auto-release@initial
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
