name: auto-release
on:
  pull_request:

jobs:
  autorelease:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: auto-release
        uses: alecsammon/gh-action-auto-release@initial
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
